{{- $secretStoreRefName := .Values.topicus.secretStore -}}
{{- range $name, $secret := .Values.topicus.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  secretStoreRef:
    name: {{ $secretStoreRefName }}
    kind: ClusterSecretStore
  refreshInterval: "10m"
  dataFrom:
  - extract:
      key: {{ .record }}
    rewrite:
      {{- range $property, $key := $secret.mappings }}
      - regexp:
          source: {{ $property }}
          target: {{ $key }}
      {{- end }}
  {{- end }}
  