apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.topicus.imagePullSecret.secretName }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.topicus.secretStore }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ `{{ .registryHost }}":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}` }}}'
  data:
  - secretKey: username
    remoteRef:
      key: "{{ .Values.topicus.imagePullSecret.keyhubUuid }}"
      property: username
  - secretKey: registryHost
    remoteRef:
      key: "{{ .Values.topicus.imagePullSecret.keyhubUuid }}"
      property: link
  - secretKey: password
    remoteRef:
      key: "{{ .Values.topicus.imagePullSecret.keyhubUuid }}"
      property: password
